### PR TITLE
Bug fixes

### PR DESCRIPTION
**Pull request by navossoc**
Hi, I'm using this extension on docker postgres:10.3-alpine.

So I did a small fix to build it on alpine and a few other fixes for bugs that I caught when I was testing the extension.

I bumped the version because sha256 hashes with rounds was really wrong.

You can run the tests with:
`make installcheck`

Hope it helps.

PS: You can create a update for 1.0 to 1.1, but I think it is easier in this case just drop the extension and create again.

[]'s

### CODE REVIEW

**Comment by leonardomdr** [comment]
Nice work @navossoc

**Comment by dverite** [comment]
Thank you Rafael, I have cherry-picked your changes up to "Bump version" which I'll do a bit differently.

**Comment by navossoc** [comment]
@dverite No problem, I don't have any experience with pgsql extensions 👍 
Probably are better ways to do it.

Let me know when the release is live.

**Comment by dverite** [comment]
Done and pushed to pgxn.org

**Pull request closed without merging**
